Algoritmo "recepcao"

Var
nome, email : caractere
idade : inteiro

Inicio
escreval("boa tarde! digite seu nome: ")
leia(nome)
limpatela()

escreval ("digite a sua idade : ")
leia(idade)
limpatela()

escreval ("digite o seu email : ")
leia(email)
limpatela()

escreval("cadastro efetuado com sucesso : ")
escreval("*************")
escreval("usuario : ",nome)
escreval("idade : ",idade)
escreval("email : ",email)
escreval("***********")

Fimalgoritmo